title: User Journey
author: Cornelis G. A. Kolbach
baseurl: http://
media: /media
markdown: kramdown
permalink: /:title
sass:
  style: :compressed
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.rb
  - Dockerfile
  - Makefile
  - README.md
  - script_en.rst
  # - src
port: 4002